name = "health-spotter"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "health_spotter"
database_id = ""

[site]
bucket = "./dist"

[build]
command = "npm run build"